export const DRAFT_ORDER_CHANGED = 'setup.DRAFT_ORDER_CHANGED';
export const DRAFT_ARRAY_CHANGED = 'setup.DRAFT_ARRAY_CHANGED';
export const NUM_OF_ROUNDS_UPDATED = 'setup.NUM_OF_ROUNDS_UPDATED';
export const SECONDS_PER_PICK_UPDATED = 'setup.SECONDS_PER_PICK_UPDATED';
export const FETCH_INITIAL_DRAFT_SETUP = 'setup.FETCH_INITIAL_DRAFT_SETUP';