export const DRAFT_ORDER_CHANGED = 'setup.DRAFT_ORDER_CHANGED';
export const SAVE_FINAL_DRAFT_ORDER = 'setup.SAVE_FINAL_DRAFT_ORDER';
export const DRAFT_ARRAY_CHANGED = 'setup.DRAFT_ARRAY_CHANGED';
export const NUM_OF_ROUNDS_UPDATED = 'setup.NUM_OF_ROUNDS_UPDATED';
export const SECONDS_PER_PICK_UPDATED = 'setup.SECONDS_PER_PICK_UPDATED';
export const DEFENSE_UPDATED = 'setup.DEFENSE_UPDATED';
export const DRAFT_TYPE_CHANGED = 'setup.DRAFT_TYPE_CHANGED';