export const PLAYER_SELECTED = 'draft.PLAYER_SELECTED';
export const PLAYER_SELECTION_MADE = 'draft.PLAYER_SELECTION_MADE';
export const CLEAR_PLAYER_SELECTION = 'draft.CLEAR_PLAYER_SELECTION';
export const AVAILABLE_PLAYERS_LOADED = 'draft.AVAILABLE_PLAYERS_LOADED';
export const PLAYERS_FETCHED = 'draft.PLAYERS_FETCHED';