export const PLAYER_SELECTED = 'draft.PLAYER_SELECTED';
export const PLAYER_SELECTION_MADE = 'draft.PLAYER_SELECTION_MADE';
export const CLEAR_PLAYER_SELECTION = 'draft.CLEAR_PLAYER_SELECTION';
export const SET_INITIAL_DRAFT_DATA = 'draft.SET_INITIAL_DRAFT_DATA';
export const DRAFT_STARTED = 'draft.DRAFT_STARTED';
export const TIMER_TICK = 'draft.TIMER_TICK';
export const PICK_TIME_EXPIRED = 'draft.PICK_TIME_EXPIRED';
export const STOP_DRAFT = 'draft.STOP_DRAFT';